### ISSUE TITLE
Help with build failure?

### ISSUE THREAD

**Issue by tksharpless** [MrNeRF/LichtFeld-Studio#1418]
Trying to build 0.5.3 on windows, following 'how to build' wiki page, from scratch (fresh clone and checkout)
cmake build failed at '[2/374] Linking CXX executable src\visualizer\lfs_shader_compiler.exe' 
with undefined symbols '__std_find_last_not_of_trivial_pos_1' and '__std_min_element_4i'
Is any expert help possible?

**Comment by tksharpless** [comment]
That link error is  due to a flaw in 2022, which Microsoft considers a feature; it can be defeated by passing _DISABLE_VECTOR_ANNOTATIONS to cl.  A compile error in the logger is cured by defining WIN32 (it should look for _WIN32).
However It seems my basic problem is having two versions of MSVCC and two of Cuda toolkit installed.  CMake and vcpkg  tend to grab VS2026  and CUDA 13 components by default,  which have some binary incompatibilities with LFS 5.  This can mostly be solved by giving explicit compiler and library paths to CMake, but  so far I have not found how to make vcpkg use the same toolset when invoked in manifest mode from CMake, and this produces some mismatches at the level of runtime libraries.
I had a lot of help from AI in figuring all this out, but I never got LFS built.

**Comment by Tsub0uchi** [comment]
having some similar issue here, I'm not able to build on 5.3

glslang.lib(hlslParseHelper.cpp.obj) : error LNK2019:
unresolved external symbol __std_find_last_not_of_trivial_pos_1

glslang.lib(ParseContextBase.cpp.obj) : error LNK2019:
unresolved external symbol __std_min_element_4i

glslang-default-resource-limits.lib(ResourceLimits.cpp.obj) :
error LNK2019: unresolved external symbol __std_find_first_not_of_trivial_pos_1

src\visualizer\lfs_shader_compiler.exe : fatal error LNK1120: 3 unresolved externals
