### PR TITLE
Fix Windows link errors from the VMM intersect cache

### PR DESCRIPTION
**Pull request by MrNeRF**
Windows CI has failed on master since #1943 (see the master push run for 1d5bb3757 and every PR since):

```
lfs_cored.lib(lfs_cored.dll) : error LNK2005: lfs::core::log_arena_failure_vram_snapshot(...) already defined
gsplat_backend_lfs.lib(Intersect.cpp.obj) : error LNK2019: unresolved external symbol __declspec(dllimport) lfs::core::VmmDeviceBuffer::... (12 members)
lfs_visualizer.dll : fatal error LNK1120: 12 unresolved externals
```

`VmmDeviceBuffer` and `log_arena_failure_vram_snapshot` are compiled into the static `lfs_core_cuda` library, not the `lfs_core` DLL, but #1943 declared them `LFS_CORE_API`. On MSVC that means `dllimport` for every consumer: `Intersect.cpp` looks for import symbols the DLL never exports (nothing inside the DLL references `vmm_device_buffer.obj`), and the snapshot function ends up both exported by the DLL and defined by `lfs_core_cuda.lib` on the same link line. Linux is unaffected because the macro is only a visibility attribute there.

Fix: no export macro on `lfs_core_cuda` symbols, matching the existing pattern (`lanczos_resize`, used from `lfs_io`), and an explicit `lfs_core_cuda` link on `gsplat_backend_lfs`, which includes the header.

### CODE REVIEW

File: src/training/rasterization/gsplat/CMakeLists.txt [hunk 1]
```diff
@@ -63,6 +63,8 @@ target_link_libraries(gsplat_backend_lfs
         CUDA::cudart
         CUDA::curand
         glm::glm
+        PRIVATE
+        lfs_core_cuda
 )
```
[the remark this answers is not in the document]
Comment (MrNeRF) [reply src/training/rasterization/gsplat/CMakeLists.txt:68]: Changed to PUBLIC in 9d4e9fa4b, matching fastlfs_backend. For the record, CMake propagates PRIVATE dependencies of static libraries to consumers for linking (as $<LINK_ONLY:...> in INTERFACE_LINK_LIBRARIES), so the previous form also linked, but the consistent form is better.
